### ISSUE TITLE
Use case

### ISSUE THREAD

**Issue by p3l1** [louib/keep-in-touch#1]
Just stumbled over this repo. Can you explain the use case of converting kdbx files to vcard and vice versa?

Thanks in advance!

**Comment by louib** [comment]
Hey Philipp!

I changed the scope of the repository. I think I'm going to work on a full-blown contact manager that uses KDBX as an encrypted backend. I'm still planning to use the vcard format, so that the contacts can be exported to other tools. I also want to enable filtering on the fields and the entries being exported to limit what is exported in an unencrypted format to other applications. For example, exporting to a mail client would only require exporting the name and email address, but not the phone number and notes.

I was working on KDBX4 support in [keepass-rs](https://github.com/sseemayer/keepass-rs), which is why I didn't work on this project in the last months. The KDBX4 feature is now being rolled out in `keepass-rs`, so I can now spend a bit more time on `keep-in-touch`.

I picked the KDBX4 format because I have experience with it, and because it's been around for a while now, which gives me confidence in using it for an encrypted backend. The format is complete enough to support merging the entries locally, so that the remote versions of the database are always encrypted. This makes it ideal for the secure management of a personal contact list. The current applications that use the KDBX4 format are very focused on password management, and changing them would be too much work and would add a lot of complexity to those applications. I think it makes sense to have a dedicated app for contact management. Further, the KDBX4 format is not extremely password specific. Arbitrary field names can be used, not just the password-related field names, like  `UserName` or `Password`.

I'm going to start the project with a very basic repl-like interface. This will be enough while I add the basic features and while I test the new version of the `keepass-rs` library. In the future, I'd like to have a responsive UI so that I can use the app on a Linux phone as well. I'm thinking about using [tauri](https://github.com/tauri-apps/tauri) for that.

Let me know if you have other questions!

**Comment by p3l1** [comment]
Hey Louis,

thank you for the very detailed response! A personal encrypted contact manager based on KDBX4 is a cool idea. I once was thinking about using KDBX4 to also store system documentation in a structured way, beside the credentials. So I am curious about, what other ideas people have for the KDBX format.

Have fun developing! I starred the repo, so I can swing by sometime :D

**Comment by louib** [comment]
> So I am curious about, what other ideas people have for the KDBX format.

One cool trick I found out is that you can find all the repos that use a library in the `dependents` tab, as in [here](https://github.com/sseemayer/keepass-rs/network/dependents).
